Require Export RealmSyncHandlerAux.Specs.access_in_par.
Require Export RealmSyncHandlerAux.Specs.get_write_value.
Require Export RealmSyncHandlerAux.Specs.handle_id_sysreg_trap.
Require Export RealmSyncHandlerAux.Specs.handle_timer_sysreg_trap.
Require Export RealmSyncHandlerAux.Specs.handle_icc_el1_sysreg_trap.
