Require Export CtxtSwitchAux.Specs.save_sysreg_state.
Require Export CtxtSwitchAux.Specs.restore_sysreg_state.
Require Export CtxtSwitchAux.Specs.save_ns_state_sysreg_state.
Require Export CtxtSwitchAux.Specs.restore_ns_state_sysreg_state.
